name: Enable Dependabot Auto Merge

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master]

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Auto Merge on Dependabot Pull Requests
        uses: dependabot/dependabot-auto-merge-action@v0.5.0
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          auto_merge: true
          labels: dependabot
          ignore_checks: false
          ignore_statuses: false
          ignore_approvals: false
